### ISSUE TITLE
Refactor entrypoint scripts

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#41]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* There is currently a lot of repeated code in the entrypoint scripts. (https://github.com/astrophpeter/blast/tree/main/app/entrypoints). This needs tidying and making more efficient. 

---

## **Describe the solution you'd like**

* Refactor entrypoint scripts removing all repeated code.

**Comment by manning-ncsa** [comment]
Recent commits such as those in #191 addressed some of this redundancy, for example in the elimination of the `docker-entrypoint.app.dev.sh` script in favor of a `DEV_MODE` environment variable that activates some logic in the `docker-entrypoint.app.sh` script. A related refactoring of initialization scripts modifies the way environment files are loaded so that they are now hierarchical: the `.env.default` file defines the default env var values, and _optionally_ you can create a `.env.dev` file with _overrides_ to these env vars.

**Comment by manning-ncsa** [comment]
@djones I recommend closing this issue.
