### ISSUE TITLE
Tidy up Docker compose volumes 

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#42]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* The docker compose files (https://github.com/astrophpeter/blast/tree/main/docker) have lots of repeating code where the volumes are defined.

---

## **Describe the solution you'd like**

* Define the volumes once in the docker compose files, or across all docker compose files.

**Comment by manning-ncsa** [comment]
In #191, we replaced the bind-mounted Docker volumes with three named volumes: `blast-db`, `blast-data`, `django-static`. This approach simplifies data management and minimizes the gap between the local dev environment and the production deployment in Kubernetes. The disadvantage is that working manually with astro data files is more cumbersome; instead of manipulating files directly on the host machine, you must interact via containers. For example, to browse and manually modify astro data files, you could use the following method:
```
# Run temporary container to access astro data
$ docker run --rm --name=blast-data --hostname=blast-data -it \
    -v blast_blast-data:/mnt/data \
    -v /tmp/blast-data:/data-stage \
    ubuntu:jammy bash

root@blast-data:/# ls /mnt/data/
cutout_cdn  dustmaps  fsps  ghost_output ...

# Copy data to the directory shared with the host
root@blast-data:/# cp -r /mnt/data/dustmaps /data-stage/
root@blast-data:/# exit
exit

# View copied data on the host
$ ls /tmp/blast-data/
dustmaps

```

**Comment by manning-ncsa** [comment]
@djones I recommend closing this issue.
